{% set name = "yaqd-gage" %}
{% set version = "2022.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/yaqd-gage-{{ version }}.tar.gz
  sha256: 7351e0959578bca6618b8437f9235fb2349c38930f78fef5a9f0685db5a01db5

build:
  number: 0
  noarch: python
  entry_points:
    - yaqd-gage-compuscope = yaqd_gage._compuscope:CompuScope.main
    - yaqd-gage-chopping = yaqd_gage._chopping:CompuScope.main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - yaqd-core >=2020.06.3
    - pip
    - flit
  run:
    - python >=3.7
    - yaqd-core >=2020.06.3
    - numpy
    - qtypes
    - toml
    - yaq-traits

test:
  imports:
    - yaqd_gage
  commands:
    - pip check
    - yaqd-gage-compuscope --help
    - yaqd-gage-chopping --help
  requires:
    - pip

about:
  home: https://yaq.fyi
  summary: yaq daemons for GaGe hardware
  dev_url: https://gitlab.com/yaq/yaqd-gage
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - untzag
    - ksunden
    - ddkohler
    - kameyer226
