{% set name = "yaqd-gage" %}
{% set version = "2021.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/yaqd-gage-{{ version }}.tar.gz
  sha256: 3db8ee2c9a4efd8e1c26013a560a30497315cb18d9581a91cee181d3fa96ff1b

build:
  number: 0
  noarch: python
  entry_points:
    - yaqd-gage-compuscope = yaqd_gage._compuscope:CompuScope.main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - yaqd-core >=2020.06.3
    - pip
    - flit
  run:
    - python >=3.7
    - yaqd-core >=2020.06.3
    - numpy

test:
  imports:
    - yaqd_gage
  commands:
    - pip check
    - yaqd-gage-compuscope --help
  requires:
    - pip

about:
  home: https://yaq.fyi
  summary: yaq daemons for GaGe hardware
  dev_url: https://gitlab.com/yaq/yaqd-gage
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - untzag
    - ksunden
    - ddkohler
    - kameyer226
